/**:
    ros__parameters:
      video_device: "/dev/video0"
      framerate: 30.0
      io_method: "mmap"
      frame_id: "camera_optical_axis"
      pixel_format: "yuyv"
      image_width: 640
      image_height: 480
      camera_name: "web_camera"
      camera_info_url: "package://simple_ball_detector/config/camera_info.yaml"
